[ERROR] There is a conflict between multiple exceptions for assigning the same variable.
[ERROR] 
[ERROR] This justification is true:
[ERROR]  --> test_default/bad/conflict.catala_en
[ERROR]   | 
[ERROR] 9 |   definition x under condition true consequence equals 0
[ERROR]   |                                ^^^^
[ERROR]   + Article
[ERROR] 
[ERROR] This justification is true:
[ERROR]  --> test_default/bad/conflict.catala_en
[ERROR]   | 
[ERROR] 8 |   definition x under condition true consequence equals 1
[ERROR]   |                                ^^^^
[ERROR]   + Article
